version: '2'

services:
  api:
    build: app/backend/.
    container_name: api
    ports:
     - "5000:5000"
    links:
     - db
    depends_on:
     - db

  www:
    build: app/frontend/.
    container_name: www
    ports:
     - "8080:80"
    links:
      - api
    depends_on:
      - api

  db:
    build: db/.
    container_name: db
    ports:
      - "5432:5432"

  worker:
    build: app/task/.
    depends_on:
      - redis
      - api

  monitor:
    build: app/task/.
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    build: redis/.
