version: '2'

services:
  api:
    build: app/backend/.
    container_name: api
    ports:
     - "5000:5000"
    links:
     - db

  www:
    build: app/frontend/.
    container_name: www
    ports:
     - "80:80"
    links:
      - api
    depends_on:
      - api

  db:
    build: db/.
    container_name: db
